spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:"

  cloud:
    config:
      label: product_service
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  group:
    mongo:
      - org.springframework.data.mongodb.core.MongoTemplate
  level:
    mongo: DEBUG

