name: test

on:
  push:
    branches: [ "master" ]


  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: http://82.97.240.173:8080/github-webhook/
          verbose: true

        
