name: test

on:
  push:
    branches: [ "master" ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.JENKINS_URL }}
          verbose: true
          webhook_type: 'json-extended'


        
